### ISSUE TITLE
oc版本

### ISSUE THREAD

**Issue by SamThicker** [a13134455667/HP-15-ax015tx-macOS11-OC-EFI#2]
您好，请问oc是哪个版本？标题是写0.6.0，readme那里写了0.6.2，但是我用几个oc configurator编辑都出问题。

**Comment by Allionc** [comment]
0.6.1

**Comment by a13134455667** [comment]
不建议使用OCC 对配置文件编辑。可以参考修改请用官方推荐的编辑器或者XCODE
