### ISSUE TITLE
双系统引导

### ISSUE THREAD

**Issue by zqqzqq2qq** [a13134455667/HP-15-ax015tx-macOS11-OC-EFI#3]
引导自己进windows，我每次都得手动进mac，然后大部分时候都卡代码，感觉进系统都靠运气，现在都不敢关机

**Comment by Allionc** [comment]
BIOS里调一下启动顺序，我之前也是靠运气进系统，但是加了英特尔WiFi驱动以后就很顺利了，不知道什么原因。

**Comment by a13134455667** [comment]
双系统 是OC 的原因  只能等更新 我也没招

**Comment by Allionc** [comment]
> 双系统 是OC 的原因 只能等更新 我也没招

麻烦老哥有时间把描述文件更新一下吧 系统版本就B6 B5 B9好几个 ，OC也0.6.0，0.6.2什么的也挺容易造成困惑的，像我这种小白琢磨了好久才搞明白

**Comment by a13134455667** [comment]
> > 双系统是OC的原因只能等更新我也没招
> 
> 麻烦老哥有时间把描述文件更新一下吧系统版本就B6 B5 B9好几个，OC也0.6.0，0.6.2什么的也挺容易造成混乱的，像

已经更新，帮忙测试一下还有冷启动或者热重启自动进入WIN10的情况吗。

**Comment by a13134455667** [comment]
> 引导自己进窗户，我每次都得手动进mac，然后大部分时候都卡代码，感觉进系统都靠运气，现在都不敢关机

已经更新，帮忙测试一下

**Comment by zqqzqq2qq** [comment]
10.7已测试，没有自动进win10的情况了，现在的问题是一直卡代码，尝试了加入intel网卡驱动，问题已解决
第二个问题是系统更新不了beat9，下载失败，不知道是不是efi的问题，或者是系统的问题？前几次更新都是没问题的

**Comment by zqqzqq2qq** [comment]
幸苦老哥了，谢谢

**Comment by a13134455667** [comment]
我这个用的是dw1560如果是网卡 卡代码，轻自行跟换



---原始邮件---
发件人: "zqqzqq2qq"<notifications@github.com&gt;
发送时间: 2020年10月7日(周三) 晚上6:48
收件人: "a13134455667/HP-15-ax015tx-macOS11-OC6.0EFI"<HP-15-ax015tx-macOS11-OC6.0EFI@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"Weisisi"<411910872@qq.com&gt;;
主题: Re: [a13134455667/HP-15-ax015tx-macOS11-OC6.0EFI] 双系统引导 (#3)




 
10.7已测试，没有自动进win10的情况了，现在的问题是一直卡代码，尝试了加入intel网卡驱动，问题已解决
 第二个问题是系统更新不了beat9，下载失败，不知道是不是efi的问题，或者是系统的问题？前几次更新都是没问题的

**Comment by a13134455667** [comment]
概率性不能进入MAC问题已确认修复。
